import { Hero } from './hero';

export const OverwatchHeroes: Hero[] = [
  { name: "Ana", normalizedName: "ana" },
  { name: "Ashe", normalizedName: "ashe" },
  { name: "Baptiste", normalizedName: "baptiste" },
  { name: "Bastion", normalizedName: "bastion" },
  { name: "Brigitte", normalizedName: "brigitte" },
  { name: "D.Va", normalizedName: "dva" },
  { name: "Doomfist", normalizedName: "doomfist" },
  { name: "Echo", normalizedName: "echo" },
  { name: "Genji", normalizedName: "genji" },
  { name: "Hanzo", normalizedName: "hanzo" },
  { name: "Junkrat", normalizedName: "junkrat" },
  { name: "Lucio", normalizedName: "lucio" },
  { name: "McCree", normalizedName: "mccree" },
  { name: "Mei", normalizedName: "mei" },
  { name: "Mercy", normalizedName: "mercy" },
  { name: "Moira", normalizedName: "moira" },
  { name: "Orisa", normalizedName: "orisa" },
  { name: "Pharah", normalizedName: "pharah" },
  { name: "Reaper", normalizedName: "reaper" },
  { name: "Reinhardt", normalizedName: "reinhardt" },
  { name: "Roadhog", normalizedName: "roadhog" },
  { name: "Soldier 76", normalizedName: "soldier76" },
  { name: "Sombra", normalizedName: "sombra" },
  { name: "Symmetra", normalizedName: "symmetra" },
  { name: "Torbjorn", normalizedName: "torbjorn" },
  { name: "Tracer", normalizedName: "tracer" },
  { name: "Widowmaker", normalizedName: "widowmaker" },
  { name: "Winston", normalizedName: "winston" },
  { name: "Wrecking Ball", normalizedName: "wreckingball" },
  { name: "Zarya", normalizedName: "zarya" },
  { name: "Zenyatta", normalizedName: "zenyatta" }
];